### ISSUE TITLE
undefined method `shuffle!'

### ISSUE THREAD

**Issue by dtelaroli** [spilliton/randumb#35]
I'm using Rails 5

with method random_by_id_shuffle

undefined method `shuffle!' for #<Person::ActiveRecord_Relation:0x000000062b3e68> Did you mean? shuffle

**Comment by spilliton** [comment]
Thanks for reporting! Will look into this hopefully sometime this weekend 👍

**Comment by spilliton** [comment]
Code was calling / checking for `to_ary` instead of `to_a`.  New version shipping shortly :)

**Comment by spilliton** [comment]
https://rubygems.org/gems/randumb/versions/0.5.1

**Comment by dtelaroli** [comment]
:+1:
